<?php
 // module/Album/view/image/image/index.phtml:

use Zend\User;
 $title = 'Images';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 

 <table class="table">
 <tr>
     <th>Id_membre</th>
     <th>l</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($images as $image) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($image->id_membre);?></td>
     <td><?php echo $this->escapeHtml($image->lien);?></td>
     <td>
         <a href="<?php echo $this->url('image',
             array('action'=>'edit', 'id' => $image->id));?>">Edit</a>
         <a href="<?php echo $this->url('image',
             array('action'=>'delete', 'id' => $image->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 <p>
    <div class="btn-group">
    </div>
     <a class="new" href="<?php echo $this->url('image', array('action'=>'add'));?>">+</a>
 </p>
 
